### ISSUE TITLE
Replace installer with WiX

### ISSUE THREAD

**Issue by Anequit** [sam-astro/Z-Sharp#3]
The installer would look much better if it was built with [WiX](https://wixtoolset.org/)

**Comment by tpguy825** [comment]
Why though? The existing one gets the job done, so it seems pointless to make another one

**Comment by dorbellprod** [comment]
With Wix, you can make your own professional website

**Comment by Anequit** [comment]
> Why though? The existing one gets the job done, so it seems pointless to make another one

the current installer looks really dated

**Comment by sam-astro** [comment]
> > Why though? The existing one gets the job done, so it seems pointless to make another one
> 
> the current installer looks really dated

The current installer is just using the default visual studio one. I do have plans in the future to make a custom one that looks better, but since it isn't very important for just using Z-Sharp and is a really small install, I think it can wait. Thank you for the suggestion though! I'll keep WiX in mind.
